### ISSUE TITLE
Icon Misalignment on Mobile

### ISSUE THREAD

**Issue by akashkbaburajan** [SimplQ/simplQ-frontend#249] opened 2020-09-21 16:11 UTC
New UI - https://mehmet.simplq.me/
There is abnormal amount of space when you take desktop view from mobile.
![Screenshot_20200921-194314](https://user-images.githubusercontent.com/16539463/93792390-1ac7ac80-fc53-11ea-86af-8a2049fd6b31.jpg)

The images and text of the features section are kinda misaligned 
![Uploading Screenshot_20200921-194337.jpg…]()

**Comment by daltonfury42** [comment] 2020-09-21 16:19
1) Desktop view from mobile - I'm not very sure if we should handle that.
2) The misalignment, we can fix.

**Comment by maaverik** [comment] 2020-09-22 18:43
I don't see any problems on normal mobile view and I agree with @daltonfury42 that desktop view from mobile isn't something we should spend time on thinking about compatibility because it's very rarely used and it's very possible that it'll end up breaking something on normal desktop or mobile view.

**Comment by daltonfury42** [comment] 2020-09-22 19:53
This issue is reproduce on Mehmet's branch. I've asked him to take a look.
Otherwise we can confirm and fix once we merge his PR

**Comment by daltonfury42** [comment] 2020-09-26 19:02
Not able to reproduce on main branch post merging. Closing, we can reopen if it comes again

**Closed by daltonfury42** 2020-09-26 19:02 UTC
