### ISSUE TITLE
Fork on Github Button Not Displaying Properly on Mobile

### ISSUE THREAD

**Issue by thehamzarocks** [SimplQ/simplQ-frontend#300] opened 2020-10-03 15:52 UTC
![image](https://user-images.githubusercontent.com/12778300/94995719-d4ad0a00-05bd-11eb-9ced-39be154d7e5c.png)

The fork on GitHub Button on the Homepage isn't rendering properly on certain Mobile Devices

Also, the layout could be better aligned since the text is too close to the simplQ logo but a bit far away from Open Source heading as visible in the image.

**Comment by rasfa98** [comment] 2020-10-03 15:54
@thehamzarocks I can fix this 🙂

**Comment by daltonfury42** [comment] 2020-10-03 15:59
@rasfa98 Please do. Thanks!

 @thehamzarocks which mobile/resolution are you on? I'm not able to reproduce this.

**Comment by rasfa98** [comment] 2020-10-03 16:00
@daltonfury42 I could reproduce this when testing in Safari simulating a mobile device 🙂

**Comment by daltonfury42** [comment] 2020-10-03 16:05
Yes, it's broken on safari

**Comment by rasfa98** [comment] 2020-10-03 16:33
@thehamzarocks The button issue has been fixed in #301 🙂

**Comment by daltonfury42** [comment] 2020-10-03 16:47
Thanks @rasfa98

**Closed by daltonfury42** 2020-10-03 16:47 UTC
Labels: You Can Do This
